version: '3.4'

services:
  themgico:
    profiles: ["backend"]
    container_name: themgico
    image: themgico
    build:
      context: .
      dockerfile: Themgico/Dockerfile

  mssql:
    profiles: ["backend"]
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:latest
